//Usando extensão REST Client (humao.rest-client)

//SITE NO RENDER
//https://appnodejs-k07h.onrender.com/

GET http://localhost:3333/alunos

###

POST http://localhost:3333/alunos
Content-Type: application/json

{
    "name": "Maria",
    "email": "maria@upf.br",
    "age": 20
}

###

PUT http://localhost:3333/alunos/...
Content-Type: application/json

{
    "name": "Jaciel",
    "email": "jaciel@upf.br",
    "age": 19
}

###

DELETE http://localhost:3333/alunos/...